<template>
    <v-card>
      <v-card-title>
        <span class="text-h5">{{ formTitle }}</span>
      </v-card-title>
      <v-card-text>
        <v-container>
          <v-row>
            <v-col
              cols="12"
              xs="12"
              lg="6"
            >
              <v-text-field
                v-model="editedItem.title"
                label="Title"
              ></v-text-field>
            </v-col>
            <v-col
              cols="12"
              xs="12"
              lg="6"
            >
              <v-text-field
                v-model="editedItem.created"
                label="Created Date"
                disabled
              ></v-text-field>
            </v-col>
            <v-col
              cols="12"
              xs="12"
              lg="6"
            >
              <v-text-field
                v-model="editedItem.description"
                label="Description"
              ></v-text-field>
            </v-col>
          </v-row>
        </v-container>
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn
          color="blue-darken-1"
          variant="text"
          @click="close"
        >
          Cancel
        </v-btn>
        <v-btn
          color="blue-darken-1"
          variant="text"
          @click="save"
        >
          Save
        </v-btn>
      </v-card-actions>
    </v-card>
</template>